QXCR1001493433 -- [ZIAP] passive cofiguration enabled Failed in automation setup on RHEL7/zabbix2

diff --git a/scripts/zabbix_hpeilo_cfg_generator.in b/scripts/zabbix_hpeilo_cfg_generator.in
--- a/scripts/zabbix_hpeilo_cfg_generator.in
+++ b/scripts/zabbix_hpeilo_cfg_generator.in
@@ -133,7 +133,12 @@ fi
 function snmptrapd_config() {
 # Get the Zabbix status
 /etc/init.d/zabbix-server status &> /dev/null
-[ $? -eq 0 ] && echo -e "\t\t\t[Done]" || echo -e "\t\t\t[Failed]"
+if [ $? -eq 0 ]; then
+        echo -e "\t\t\t[Done]"
+else
+        systemctl status zabbix-server &> /dev/null
+        [ $? -eq 0 ] && echo -e "\t\t\t[Done]" ||echo -e "\t\t\t[Failed]"
+fi
 
 # Check if the Zabbix Server is started.
 if [ $? -ne 0 ]; then
